### ISSUE TITLE
error when run train.py

### ISSUE THREAD

**Issue by baiyuting** [minicheshire/Robust-Prefix-Tuning#2]
when run train.py , I got error message

['NVIDIA A40']
2022-04-25 07:39:28,908 - 0:01:22 - 0.0s - INFO - __main__ - args = Namespace(PMP_iter=5, PMP_lr=5e-05, REG_TYPE_KEYS=['mas', 'ewc'], adam_epsilon=0.0001, add_task_tokens=False, attack='clean', control_len=1, data_dir='data', debug=False, decay_style='linear', device=2, device_ids=[2], dynamic_epochs=False, fp32=True, gen_lm_sample_percentage=0.05, learning_rate=5e-05, lm_lambda=0.25, logging_steps=1000, lr_schedule='warmup_linear', max_grad_norm=1, max_len=1024, max_n_epochs=9, memory_sizes=[45634.0], mid_dim=512, min_batch_size=4, min_n_steps=1500, model_dir_root='saved_models/gpt2-medium/finetune/sst', model_name='gpt2-medium', n_gpus=1, n_train_epochs={'sst': 100}, n_warmup_ratio=0.005, n_workers=4, olayer=24, pgd_ball='word', preseqlen=10, qp_margin=0.5, real_sample=False, reg_lambda=1.0, seed=101, seq_train_type='finetune', skip_tasks=None, tasks=['sst'], temperature_lm=1.0, temperature_qa=1.0, test_batch_size=[5476], test_ep=100, tokens_weight=5, top_k_lm=20, top_k_qa=20, top_p_lm=0.0, top_p_qa=0.0, train_batch_size=[5476], tune_layer=3, uat_epoch=10, uat_len=3, unbound=0, use_sep=False, weight_decay=0.01)
2022-04-25 07:39:28,909 - 0:01:22 - 0.0s - INFO - __main__ - start to train { task: ['sst'], seq train type: finetune }
2022-04-25 07:39:28,909 - 0:01:22 - 0.0s - INFO - __main__ - extra training data size: 0
2022-04-25 07:40:05,900 - 0:01:59 - 37.0s - INFO - __main__ - gen token = __gen__ , gen token id = 50260
torch.Size([1024])
tensor([-0.0115,  0.0031, -0.0073,  ..., -0.0526, -0.1757,  0.0257],
       device='cuda:2')
torch.Size([10, 1024])
torch.Size([512, 1024]) torch.Size([49152, 512])
Traceback (most recent call last):
  File "/root/Robust-Prefix-Tuning/train.py", line 149, in <module>
    model = train([task_id], model)
  File "/root/Robust-Prefix-Tuning/train.py", line 69, in train
    train_qadata = QADataset(train_dataset, "train", SPECIAL_TOKEN_IDS[tasks[0]], train_extra_data)
  File "/root/Robust-Prefix-Tuning/utils.py", line 162, in __init__
    with open(data_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/sst_to_squad-train-v2.0.json'

It seems that train data is lost

**Comment by minicheshire** [comment]
Hi @baiyuting , thanks for your interest in our work! 

You can get the training data from this link: https://drive.google.com/file/d/1842WbRH6y3TYuXuURfFIIvm4w6mTqYXT/view?usp=sharing . 

P.S. We've also released our trained prefix P_θ 's on different benchmarks in the file. You can start with the released prefixes if you want to try out robust prefix-tuning first :)
